# -*- coding: utf-8 -*-
"""Visualizing Audio with Spectrum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EWUkUw9PtIIcHnrZura0s8_wQ4-6Jx7Y

#Import Library
"""

import numpy as np

import pandas as pd

import tensorflow as tf

import librosa

import matplotlib.pyplot as plt

import librosa.display

"""#Visualzing Audio

#Visualizing Genre Jazz
"""

N_FFT = 2048
N_MELS = 128
HOP_LEN = 512

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Citra_1/Citra_1_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Citra_1/Citra_1_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Citra_1/Citra_1_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Citra_2/Citra_2_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Citra_2/Citra_2_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Citra_2/Citra_2_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Glenn_3/Glenn_3_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Glenn_3/Glenn_3_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Glenn_3/Glenn_3_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Glenn_4/Glenn_4_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Glenn_4/Glenn_4_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Glenn_4/Glenn_4_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Payung_5/Payung_5_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Payung_5/Payung_5_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Payung_5/Payung_5_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Petra_6/Petra_6_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Petra_6/Petra_6_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Petra_6/Petra_6_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Raisa_7/Raisa_7_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Raisa_7/Raisa_7_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Raisa_7/Raisa_7_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Tulus_8/Tulus_8_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Tulus_8/Tulus_8_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Tulus_8/Tulus_8_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Tulus_9/Tulus_9_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Tulus_9/Tulus_9_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Tulus_9/Tulus_9_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Tulus_10/Tulus_10_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Tulus_10/Tulus_10_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_jazz/Tulus_10/Tulus_10_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

"""#Visualizing Genre Pop"""

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Agnes_1/Agnes_1_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Agnes_1/Agnes_1_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Agnes_1/Agnes_1_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Arsy_2/Arsy_2_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Arsy_2/Arsy_2_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Arsy_2/Arsy_2_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Astrid_3/Astrid_3_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Astrid_3/Astrid_3_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Astrid_3/Astrid_3_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Audy_4/Audy_4_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Audy_4/Audy_4_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Audy_4/Audy_4_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Brisia_5/Brisia_5_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Brisia_5/Brisia_5_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Brisia_5/Brisia_5_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Hivi_6/Hivi_6_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Hivi_6/Hivi_6_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Hivi_6/Hivi_6_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Judika_7/Judika_7_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Judika_7/Judika_7_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Judika_7/Judika_7_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Lyla_8/Lyla_8_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Lyla_8/Lyla_8_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Lyla_8/Lyla_8_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Maudy_9/Maudy_9_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Maudy_9/Maudy_9_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Maudy_9/Maudy_9_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Melly_10/Melly_10_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Melly_10/Melly_10_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_pop/Melly_10/Melly_10_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

"""#Visualizing Genre Rock"""

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Cokelat_1/Cokelat_1_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Cokelat_1/Cokelat_1_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Cokelat_1/Cokelat_1_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Jrocks_2/Jrocks_2_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Jrocks_2/Jrocks_2_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Jrocks_2/Jrocks_2_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Jamrud_3/Jamrud_3_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Jamrud_3/Jamrud_3_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Jamrud_3/Jamrud_3_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/KMI_4/KMI_4_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/KMI_4/KMI_4_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/KMI_4/KMI_4_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Kotak_5/Kotak_5_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Kotak_5/Kotak_5_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Kotak_5/Kotak_5_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Kotak_6/Kotak_6_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Kotak_6/Kotak_6_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Kotak_6/Kotak_6_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Kotak_7/Kotak_7_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Kotak_7/Kotak_7_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Kotak_7/Kotak_7_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Nidji_8/Nidji_8_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Nidji_8/Nidji_8_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Nidji_8/Nidji_8_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Rocket_9/Rocket_9_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Rocket_9/Rocket_9_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Rocket_9/Rocket_9_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Super_10/Super_10_a.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Super_10/Super_10_b.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

y, sfr = librosa.load('/content/drive/My Drive/Data Set TA/data_set/data_train/set_rock/Super_10/Super_10_c.mp3')

melSpec = librosa.feature.melspectrogram(y=y, sr=sfr, n_mels=N_MELS,hop_length=HOP_LEN, n_fft=N_FFT)
melSpec_dB = librosa.power_to_db(melSpec, ref=np.max)

librosa.display.specshow(melSpec_dB)

"""#Pre-proses Images"""

path='../content/drive/My Drive/Data Set TA/data_set/image_proses'

data_gen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255., validation_split=0.2)

(img_height, img_width)=(299,299)
batch_size=32
train_generator = data_gen.flow_from_directory(
    path,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical',
    subset='training') # set as training data

validation_generator = data_gen.flow_from_directory(
    path, # same directory as training data
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical',
    subset='validation') # set as validation data

from tensorflow.keras.applications import Xception

base_model=Xception(include_top=False,input_shape=(299,299,3))

# Freeze the base_model
base_model.trainable = False

# Create new model on top
inputs = tf.keras.Input(shape=(299,299,3))

x = base_model(inputs, training=False)
x = tf.keras.layers.GlobalAveragePooling2D()(x)
x = tf.keras.layers.Dropout(0.2)(x)  # 1st improove Regularize with dropout
x = tf.keras.layers.Dense(512,activation='relu')(x)
x = tf.keras.layers.Dropout(0.2)(x) # 2st improove Regularize with dropout
x = tf.keras.layers.Dense(64,activation='relu')(x)
outputs = tf.keras.layers.Dense(10,activation='softmax')(x)

model = tf.keras.Model(inputs, outputs)
model.summary()

